global:
  db:
    database: demo-board
    port: 3306
    username: demo-board
    password: board1234

replicaCount: 1
profile: dev

image:
  repository: aoc55soft/demo-board
  pullPolicy: IfNotPresent
  tag: ""

podLabels: {}

# todo NodePort 고도화
service:
  type: ClusterIP
  port: 8080
