sever:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # jdbc:mariadb://mariadb:3306/demo-board
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/demo-board
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
      hibernate:
        ddl-auto: none

logging.level.root: info

---
spring:
  config.activate.on-profile: local
  application:
    name: Demo Board - Local
  banner:
    location: classpath:banner/banner-local.txt
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demoboard
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config.activate.on-profile: dev
  application:
    name: Demo Board - DEV
  banner:
    location: classpath:banner/banner-dev.txt

---
spring:
  config.activate.on-profile: prod
  application:
    name: Demo Board - PROD
  banner:
    location: classpath:banner/banner-prod.txt
