sever:
  port: 8080

spring:
  datasource:
    username: demoboard
    password: demo1234!
  jpa:
      hibernate:
        ddl-auto: none

---
spring:
  config.activate.on-profile: local
  application:
    name: Demo Board - Local
  banner:
    location: classpath:banner/banner-local.txt
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: create-drop

logging.level.root: info

---
spring:
  config.activate.on-profile: dev
  application:
    name: Demo Board - DEV
  banner:
    location: classpath:banner/banner-dev.txt
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/demo-board

logging.level.root: info

---
spring:
  config.activate.on-profile: prod
  application:
    name: Demo Board - PROD
  banner:
    location: classpath:banner/banner-prod.txt
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/demo-board

logging.level.root: info
