apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-board.fullname" . }}-db
data:
  DB_DATABASE: "{{ .Values.global.db.database }}"
  DB_URL: "{{ .Release.Name -}}-mariadb"
  DB_PORT: "{{ .Values.global.db.port }}"
  DB_USERNAME: "{{ .Values.global.db.username }}"
  DB_PASSWORD: "{{ .Values.global.db.password }}"