apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-board.fullname" . -}}-db
data:
  DB_URL: "{{ .Values.db.url }}"
  DB_PORT: "{{ .Values.db.port }}"
  DB_USERNAME: "{{ .Values.db.username }}"
  DB_PASSWORD: "{{ .Values.db.password }}"
