apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-board.fullname" . }}
  labels:
     {{- include "demo-board.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-board.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "demo-board.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{- .Values.image.tag | default .Chart.AppVersion -}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: USE_PROFILE
              value: "{{ .Values.profile }}"
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "demo-board.fullname" . -}}-db
                  key: DB_URL
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "demo-board.fullname" . -}}-db
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "demo-board.fullname" . -}}-db
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "demo-board.fullname" . -}}-db
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080
              name: demo-board
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          # Resource 제한 없음