apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-board
  labels:
    app: demo-board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-board
  template:
    metadata:
      labels:
        app: demo-board
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: demo-board
          image: docker.io/aoc55soft/demo-board:1.0.0-amd
          imagePullPolicy: IfNotPresent
          env:
            - name: USE_PROFILE
              value: "local"
            # configmap?
            - name: DB_URL
              value: "local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: "demo-board"
            - name: DB_PASSWORD
              value: "board1234"
          ports:
            - containerPort: 8080
              name: demo-board
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          # Resource 제한 없음


